package com.mattl_nz.dex.core.security

import com.mattl_nz.dex.core.model.PAIRING_QR_VERSION
import com.mattl_nz.dex.core.model.PairingQrPayload
import kotlinx.serialization.json.Json

sealed interface QrPairingValidationResult {
    data class Success(val payload: PairingQrPayload) : QrPairingValidationResult
    data class ScanError(val message: String) : QrPairingValidationResult
    data class BridgeUpdateRequired(val message: String) : QrPairingValidationResult
}

object QrPairingValidator {
    private val json = Json { ignoreUnknownKeys = true }

    fun validate(code: String, nowMillis: Long = System.currentTimeMillis()): QrPairingValidationResult {
        val payload = try {
            json.decodeFromString<PairingQrPayload>(code)
        } catch (_: Exception) {
            return if (looksLikePairingPayload(code)) {
                QrPairingValidationResult.BridgeUpdateRequired(
                    "This QR code looks like it came from an older Remodex bridge. Update the bridge on your Mac and scan again."
                )
            } else {
                QrPairingValidationResult.ScanError(
                    "Not a valid Remodex pairing code. Scan a QR generated by the current bridge."
                )
            }
        }

        if (payload.v != PAIRING_QR_VERSION) {
            return QrPairingValidationResult.BridgeUpdateRequired(
                "This QR code was generated by a different Remodex package version. Update the bridge on your Mac and generate a new code."
            )
        }
        if (payload.relay.isBlank()) {
            return QrPairingValidationResult.ScanError("QR code is missing the relay URL.")
        }
        if (payload.sessionId.isBlank()) {
            return QrPairingValidationResult.ScanError("QR code is missing the session id.")
        }
        if (payload.expiresAt + 60_000L < nowMillis) {
            return QrPairingValidationResult.ScanError("This pairing QR code has expired. Generate a new one from the Mac bridge.")
        }
        return QrPairingValidationResult.Success(payload)
    }

    private fun looksLikePairingPayload(code: String): Boolean {
        return listOf("relay", "sessionId", "macDeviceId", "macIdentityPublicKey", "expiresAt", "\"v\"")
            .any { code.contains(it) }
    }
}
